version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - run: mkdir -p /tmp/workdir
      - persist_to_workspace:
          root: /tmp/workspace

      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: build
          command: |
            docker pull alpine
            docker save alpine > /tmp/workspace/alpine-image.tar
            docker images

  deploy:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: deploy
          command: |
            docker images
            ls /tmp/workspace
            docker load < /tmp/workspace/alpine-image.tar
            docker images

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
