version: 2.0
jobs:
  build:
    docker:
      - image: gitlab/dind

    working_directory: /tmp/workspace

    steps:
      - run: mkdir -p /tmp/workspace/docker
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./

      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: build
          command: |
            docker pull alpine
            docker save alpine > docker/alpine-image.tar
            ls docker
            docker images

  deploy:
    docker:
      - image: gitlab/dind

    working_directory: /tmp/workspace
    steps:
      - run: mkdir -p /tmp/workspace
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: deploy
          command: |
            ls
            docker images
            ls docker
            docker load < docker/alpine-image.tar
            docker images

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
