version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            echo foo

  deploy:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - run:
          name: deploy
          command: |
            echo Deployyyyyyyyyyyyyyyyyyy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build
